/* main.c generated by valac, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define WINDOWS_TYPE_MAIN_WINDOW (windows_main_window_get_type ())
#define WINDOWS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINDOWS_TYPE_MAIN_WINDOW, WindowsMainWindow))
#define WINDOWS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINDOWS_TYPE_MAIN_WINDOW, WindowsMainWindowClass))
#define WINDOWS_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINDOWS_TYPE_MAIN_WINDOW))
#define WINDOWS_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINDOWS_TYPE_MAIN_WINDOW))
#define WINDOWS_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINDOWS_TYPE_MAIN_WINDOW, WindowsMainWindowClass))

typedef struct _WindowsMainWindow WindowsMainWindow;
typedef struct _WindowsMainWindowClass WindowsMainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



WindowsMainWindow* windows_main_window_new (void);
WindowsMainWindow* windows_main_window_construct (GType object_type);
GType windows_main_window_get_type (void);
gint _vala_main (char** args, int args_length1);



gint _vala_main (char** args, int args_length1) {
	gint result = 0;
	WindowsMainWindow* win;
	gtk_init (&args_length1, &args);
	win = g_object_ref_sink (windows_main_window_new ());
	gtk_main ();
	result = 0;
	_g_object_unref0 (win);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}




